name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "wbb"
          replace: "ftb"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'SeD Replacer'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Fintech
          commit_user_email: toluwasechristopher45@gmail.com
          commit_author: Fintech <toluwasechristopher45@gmail.com>
